In [1]:
import pandas as pd
df = pd.read_csv("hw2dataNorm.csv")

In [2]:
df=df.iloc[:,1:]
# fullData=df.to_numpy()

In [3]:
fullData = df.to_numpy()

In [4]:
fullData

array([[ 0.8815816 ,  1.04637137,  1.19253608, ..., -1.60292621,
        -0.16195588,  1.        ],
       [ 1.53868944,  1.7414904 , -2.0183408 , ...,  0.27748574,
        -0.99310669,  1.        ],
       [-0.08979522, -0.95209585,  0.89957286, ...,  0.38864925,
        -1.55240038,  1.        ],
       ...,
       [ 0.25304366,  0.95948149, -0.2254059 , ...,  1.66492267,
        -0.89728504,  0.        ],
       [-1.68970996, -1.42999018,  1.23941019, ..., -0.29286325,
         0.33915503,  0.        ],
       [-1.28973128,  0.26436246, -0.11993914, ...,  0.89119704,
         0.1618081 ,  1.        ]])

In [5]:
X = fullData[:,0:10]

In [6]:
y = fullData[:,10]

In [7]:
import numpy as np

In [8]:
def sigmoidLikelihood(X, y , w):
    
    rows,cols = X.shape
    
    dummy = np.ones(rows)
    dummy = dummy.reshape((rows,1))
    X1 = np.append(X,dummy,axis=1)
    
    def sigmoid(w_vector,xi):
        return (1/(1+ np.exp(-(np.dot(w_vector,xi)))))
    
    def pseudo_probability(w,xi,yi):
        return ((1-sigmoid(w,xi))**(1-yi))*((sigmoid(w,xi))**yi)
    
    vector = list()
    for row in range(len(y)):
        vector.append(pseudo_probability(w,X1[row,:],y[row]))
        
    return np.array(vector)  

In [9]:
# 0.05**248

In [10]:
# 0.05**249

In [11]:
# we see that, at 249 multipications of likelihoods, the resultant becomes 0

In [12]:
a = np.array([0.05]*249)

In [13]:
np.sum(np.log(a))

-745.9373361149437

In [14]:
# ans 2.b = -745.93733

In [15]:
# assume initial guesses for w vector incorporating the offset
w = np.zeros(len(X[0])+1)

In [16]:
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
K = 10

In [18]:
def log_Likelihood(X, y, W):
    
    rows, cols = X.shape
    
    def sigmoid(w_vector,xi):
        return (1/(1+ np.exp(-(np.sum(w_vector*xi)))))
    
    
    
    def pseudo_probability(w_vector,xi,yi):
        
        yi = int(yi)
        
        f = (1 - sigmoid(w_vector,xi))**(1-yi)
        s = (sigmoid(w_vector,xi))**yi
        
        res = f * s
        return res
    
    
    new_array = list()
    
    for i in range(rows):
        new_array.append(pseudo_probability(W,X[i],y[i]))

    new_array = np.array(new_array)
    log_like = np.sum(np.log(new_array))  
    return log_like

In [19]:
def updateRule(X, y, w):
    
    learning_rate = 0.01
    
    def sigmoid(w_vector,xi):
        sig =  (1/(1+ np.exp(-(np.dot(w_vector,xi)))))

        return sig
    
    
    rows, cols = X.shape
    
    # initialize gradient vector to all zeros
    grad_vector = np.zeros(cols)
    for i in range(rows):
        
        
        for j in range(cols):
            
            xj = X[i][j]
            yi = y[i]
            
            grad_vector[j] += xj*(yi - sigmoid(w,X[i])) # calculating gradients based on all of dataset
            
    
    
    
    for j in range(cols):        # this loop will be removed in the learnlogisticFast function
        w[j] += learning_rate*grad_vector[j]

        
    return w



def learnLogistic(w0, X, y, K):
    
    log_likelihood = list()
    rows,cols = X.shape
    
    dummy = np.ones(rows)
    dummy = dummy.reshape((rows,1))
    X1 = np.append(X,dummy,axis=1)
    
    
    
    for loop in range(K):
    
    
        w0 = updateRule(X1, y, w0)
        
        log_likelihood.append(log_Likelihood(X1,y,w0))
            
    
    
    
        
    return w0, np.array(log_likelihood)

In [20]:
def updateRuleFast(X, y, w):
    
    learning_rate = 0.01
    
    def sigmoid(w_vector,xi):
        sig =  (1/(1+ np.exp(-(np.dot(w_vector,xi)))))

        return sig
    
    
    rows, cols = X.shape
    
    # initialize gradient vector to all zeros
    grad_vector = np.zeros(cols) # reset updates
    for i in range(rows):
        
        yi = y[i]
            
        grad_vector += X[i]*(yi - sigmoid(w,X[i])) # calculating gradients based on all of dataset
            
    
    
    # using Vectorization to update w skipping the for loop
    
    new_w = w + (learning_rate)*grad_vector
    w = new_w
            
        
    return w


def learnLogisticFast(w0, X, y, K):
    
    log_likelihood = list()
    rows,cols = X.shape
    
    dummy = np.ones(rows)
    dummy = dummy.reshape((rows,1))
    X1 = np.append(X,dummy,axis=1)
    
    
    
    for loop in range(K):
    
    
        w0 = updateRuleFast(X1, y, w0)
        
        log_likelihood.append(log_Likelihood(X1,y,w0))


    return w0, np.array(log_likelihood)

In [21]:
import time

In [22]:
# assume initial guesses for w vector incorporating the offset
w0 = np.zeros(len(X[0])+1)
K = 10 # number of loops

In [23]:
timeStart = time.time()
w, LHistory = learnLogistic(w0, X, y, K)
timeEnd = time.time()
a = timeEnd-timeStart

In [24]:
print(w)
print(LHistory)

[ 0.31582482 -0.21379867  0.66178671  0.44060446 -0.09422403  0.83404356
  4.76143471 -1.12802087  1.15673754 -3.63355023  0.45697398]
[-497.27729395 -463.3764476  -457.44326896 -453.55682843 -450.3679247
 -447.60265937 -445.19301184 -443.10375312 -441.30709101 -439.77603386]


In [25]:
print(a)

1.0268754959106445


In [26]:
timeStart = time.time()
w1 = np.zeros(len(X[0])+1)
wFast, LHistoryFast = learnLogisticFast(w1, X, y, K)
timeEnd = time.time()
b = timeEnd-timeStart
print(b)

0.3693704605102539


In [27]:
print(wFast)
print(LHistoryFast)

[ 0.31582482 -0.21379867  0.66178671  0.44060446 -0.09422403  0.83404356
  4.76143471 -1.12802087  1.15673754 -3.63355023  0.45697398]
[-497.27729395 -463.3764476  -457.44326896 -453.55682843 -450.3679247
 -447.60265937 -445.19301184 -443.10375312 -441.30709101 -439.77603386]


In [28]:
print(a-b)


0.6575050354003906


In [29]:
def logisticClassify(X, w):
    
    rows,cols = X.shape
    
    dummy = np.ones(rows)
    dummy = dummy.reshape((rows,1))
    X1 = np.append(X,dummy,axis=1)
    
    classLabels = list()
    for i in range(rows):
        
        if np.dot(w,X1[i]) > 0:
            classLabels.append(1)
        else:
            classLabels.append(0)
            
    return np.array(classLabels)

In [30]:
labels = logisticClassify(X,w)

In [31]:
print(labels)

[1 1 1 ... 0 0 1]


In [32]:
c,d = 0,0

for i in range(len(y)):
    if y[i] == 0 and labels[i] == 0:
        c+=1

    elif y[i] == 1 and labels[i] == 1:
        d +=1

In [33]:
print(c,d)

903 994


In [34]:
print('accuracy: ',(c+d)/len(y))

accuracy:  0.9485
